Inte challenge1
simonxcm/DonkeySchool pull request #1
Opened 2021-09-21 14:18 UTC by simonxcm

2021-09-22 10:37 UTC, Sarawilong requested changes

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <div class="conteneur-nav">
indentation

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <h4>projet-1</h4>
Majuscule à Projet

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <h4>projet-2</h4>
idem

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <h4>projet-3</h4>
idem

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +        <section  class="etudes">
class="studies" ? ou training... en anglais

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                    <button class="article-button">commentaires</button>
Majuscule

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                    <button class="article-button">commentaires</button>
majuscule

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <label>Nom & Prénom
attribut for ?

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                    <input name="name">
attribut id ?  attribut type ?

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <label>E-mail
for

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                    <input name="E-mail">
id et type

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +            </form>
pas besoin de mettre autant de form dans ton formulaire tu peux mettre plsuieurs label et plusieurs input car tu envois qu'un seul formulaire et non pas plusoeur formulaire et tu finis par ton buton pour envoyé et là tu fermes la balise form

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                <label>Votre message
idem

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +                    <input name="votre_message">
idem

2021-09-22 10:37 UTC, Sarawilong commented on Integration/portfolio.html
> +<link rel="stylesheet" href="">
indent

2021-09-23 19:55 UTC, simonxcm commented on Integration/portfolio.html
> +                <div class="conteneur-nav">
Hello Sarawi je n'avais même pas vu que j'avais toutes ces corrections de ta part sur cette partie de Github. Je m'occupe de tout ça demain !

2021-09-23 20:03 UTC, simonxcm reviewed
Merci pour ton retour, j'ai corrigé.

2021-09-23 20:04 UTC, merged

2021-09-23 20:18 UTC, simonxcm reviewed
Corrections done thank you!